version: "3.8"

services:
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    volumes:
      - kafka-volume:/bitnami
    networks:
      - crypto-alert
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT


  alert-service:
    build: ./alerts-service
    ports:
      - 3000:3000
    networks:
      - crypto-alert

  email-service:
    build: ./email-service
    ports:
      - 3001:3001
    networks:
      - crypto-alert

volumes:
  kafka-volume:

networks:
  crypto-alert: