version: "3.8"

services:
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    volumes:
      - kafka-volume:/bitnami
    networks:
      - app
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  alert-service:
    build: ./alert-service
    networks:
      - app
    ports:
      - 3000:3000
    depends_on:
      - kafka

  email-service:
    build: ./email-service
    networks:
      - app
    depends_on:
      - kafka

volumes:
  kafka-volume:

networks:
  app:
    driver: bridge
